default_language_version:
  python: python3.10
default_stages:
  - commit
  - push
fail_fast: false  # See every failure, not just first.
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: check-nbstripout-installed
        name: check-nbstripout-installed
        entry: nbstripout --is-installed
        language: system
        types: [jupyter]
